### ISSUE TITLE
Can it create the labels but without the border surrounding the text?

### ISSUE THREAD

**Issue by Derick2k** [xsrf/easyeda-labelmaker#4]
Apologies if this is the wrong place to ask this.

Can the labels be created where the text is filled like normal text and no border?
I ask this because the EasyEDA text tool is horrendous with its default font being the only one that can be resized.
Your extension allows me to use different fonts and resize them as I need which has been very helpful.

Thank you for creating this and for your time.

**Comment by xsrf** [comment]
Well, you can't resize text labels in EasyEDA by dragging them, but you can enter any text size you need. And you can add any ttf font you want via the `Fonts Management` button on the texts properties panel. You're not limited to the default font. I don't see an issue there.
For regular text labels, the internal tool is way more better than mine 🤔

But to answer the question... No, you can't, sorry.
