### ISSUE TITLE
Font not Found!

### ISSUE THREAD

**Issue by toogooda** [xsrf/easyeda-labelmaker#6]
I love this ext I use it on every PCB, I have recently moved to linux (Ubuntu) and find that you extension shows error as it cannot find fonts

![image](https://user-images.githubusercontent.com/9059644/136716142-278d5ead-2c08-400b-a7b2-057bd11393ae.png)

Is this ext only for windows?

Used ttf-mscorefonts-installer to install standard windows ttf but did not help

Same issue on Mac, can see three fonts in fonts manager, and tried refresh cache.

Thanks

**Comment by toogooda** [comment]
OK not sure why the three already installed did not work but to fix this on both Mac and Linux you need to install another font, once installed you select "Rebuild Fonts Cache" then it works.

**Comment by xsrf** [comment]
Interesting... EasyEDA doesn't come with ttf fonts by default but one font is supplied and should be installed by the extension itself. Not sure why that didn't work for you 🤔
