### ISSUE TITLE
font not found!

### ISSUE THREAD

**Issue by Ging-H** [xsrf/easyeda-labelmaker#8]
font not found and cannot be used
![image](https://user-images.githubusercontent.com/56352028/195550353-490bb7e8-f807-43c8-84cb-3e1a137ebee1.png)

**Comment by xsrf** [comment]
Did you download and install the extension from the [Releases](https://github.com/xsrf/easyeda-labelmaker/releases/tag/v1.1) or did you clone it? There is a `.ttf` font included in the release but not in the cloned repository.
If you cloned the repository download the zip and install the `.ttf` - or any other `.ttf` - as described in the [readme](https://github.com/xsrf/easyeda-labelmaker#font).
Or remove the extension and install it again via the release zip.

**Comment by Ging-H** [comment]
ok, it works for me, thank you !
